version: '3'

services:

  api:
    image: josecastillolema/api
    ports:
      - "3000:5000"
    depends_on:
      - mysql
    deploy:
      replicas: 3
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      #update_config:
      #  parallelism: 1
      #  delay: 10is
      mode: replicated
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: senhaFiap
    deploy:
      replicas: 1
     # resources:
     #   limits:
     #     cpus: "0.1"
     #     memory: 50M
      restart_policy:
        condition: on-failure

volumes:
  db-data:
