version: '2'
services:

  api:
    build: api/.
    ports:
      - "4000:5000"
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: senhaFiap
